<!-- source: http://dzidziusiowo.pl -->
<?php
	$namesArray = Array(
		'name' => array('Zuzanna',
						'Julia',
						'Lena',
						'Maja',
						'Hanna',
						'Zofia',
						'Amelia',
						'Alicja',
						'Aleksandra',
						'Natalia',
						'Oliwia',
						'Maria',
						'Wiktoria',
						'Emilia',
						'Antonina',
						'Laura',
						'Anna',
						'Iga',
						'Pola',
						'Liliana',
						'Antoni',
						'Jakub',
						'Szymon',
						'Jan',
						'Filip',
						'Franciszek',
						'Mikołaj',
						'Aleksander',
						'Kacper',
						'Wojciech',
						'Adam',
						'Michał',
						'Marcel',
						'Wiktor',
						'Stanisław',
						'Bartosz',
						'Mateusz',
						'Igor',
						'Nikodem',
						'Alan'),
						
		'origin' => array('biblijnego',
						'starorzymskiego',
						'greckiego',
						'starorzymskiego',
						'semickiego',
						'greckiego',
						'germańskiego',
						'greckiego',
						'greckiego',
						'łacińskiego',
						'łacińskiego',
						'hebrajskiego',
						'łacińskiego',
						'łacińskiego',
						'łacińskiego',
						'łacińskiego',
						'hebrajskiego',
						'łacińskiego',
						'greckie',
						'łacińskiego',
						'łacińskiego',
						'biblijnego',
						'hebrajskiego',
						'hebrajskiego',
						'greckiego',
						'germańskiego',
						'greckiego',
						'starogreckiego',
						'perskiego',
						'słowiańskie',
						'hebrajskiego',
						'hebrajskiego',
						'łacińskiego',
						'łacińskiego',
						'staropolskiego',
						'aramejskiego',
						'biblijnego',
						'germańskiego',
						'greckiego',
						'celtyckiego'),

		'nameDay' => array('18 lutego, 24 maja, 11 sierpnia',
						'8 kwietnia, 16 kwietnia, 22 maja, 27 lipca, 30 lipca, 10 grudnia',
						'10 listopada',
						'9 kwietnia, 1 maja',
						'5 stycznia, 29 stycznia, 26 lipca',
						'15 maja, 30 września',
						'30 marca, 10 sierpnia',
						'1 marca, 10 września, 11października',
						'20 marca, 21 kwietnia, 18 maja, 2 października',
						'27 lipca, 1 grudnia, 21 grudnia',
						'5 marca',
						'23 stycznia, 3 maja, 2 lipca, 22 lipca, 15 sierpnia, 26 sierpnia, 8 września, 12 września, 7 października, 16 listopada',
						'20 maja, 23 grudnia',
						'5 stycznia, 23 maja, 24 czerwca, 30 czerwca, 19 sierpnia, 24 sierpnia, 24 listopada',
						'1 marca, 3 maja, 31 października, 12 czerwca',
						'17 czerwca, 28 sierpnia',
						'10 stycznia, 27 lutego, 7 czerwca, 9 czerwca, 23 czerwca, 15 lipca, 26 lipca, 1 września',
						'11 maja',
						'9 lutego, 23 września.',
						'14 lutego',
						'12 stycznia, 17 stycznia, 6 lutego, 1 marca, 28 marca, 3 kwietnia, 10 kwietnia, 10 maja, 7 czerwca, 13 czerwca, 5 lipca, 10 lipca, 24 lipca, 3 września, 24 października, 7 listopada, 28 grudnia',
						'5 lutego, 14 marca, 3 kwietnia, 17 kwietnia, 30 kwietnia,  1 maja, 6 maja, 1 czerwca, 5 lipca, 14 lipca,   25 lipca, 6 sierpnia, 21 października, 28 października',
						'5 stycznia, 16 lutego, 24 marca, 20 kwietnia, 16 maja, 18 lipca, 3 września, 28 października',
						'8 lutego, 8 marca, 27 marca, 7 kwietnia, 13 kwietnia, 27 maja, 12 czerwca, 24 czerwca, 26 czerwca, 12 lipca, 4 sierpnia, 29 sierpnia, 13 września, 3 października, 19 października, 13 listopada, 27 grudnia',
						'11 kwietnia, 1 maja, 6 maja, 26 maja, 10 lipca, 23 sierpnia, 13 września, 22 października',
						'29 stycznia, 17 lutego, 9 marca, 2 kwietnia, 11 maja, 4 czerwca, 14 lipca, 21 sierpnia, 17 września, 4 października, 10 października, 24 listopada, 3 grudnia, 22 grudnia',
						'14 lutego, 21 marca, 9 maja, 19 maja, 2 czerwca, 6 lipca, 9 lipca, 13 października, 6 grudnia',
						'15 stycznia, 26 lutego, 10 marca, 18 marca, 20 marca, 24 kwietnia, 3 maja, 18 maja, 10 lipca, 17 lipca, 11 sierpnia, 28 sierpnia, 13 września, 11 października, 12 grudnia',
						'6 stycznia',
						'23 kwietnia',
						'6 kwietnia, 24 grudnia',
						'2 marca, 14 marca, 10 kwietnia, 4 maja, 8 maja, 23 maja, 20 czerwca, 5 lipca, 25 sierpnia, 6 września, 29 września',
						'16 stycznia, 10 marca, 14 sierpnia',
						'22 stycznia, 25 lutego, 16 marca, 12 kwietnia, 8 maja, 28 maja, 21 lipca, 28 lipca, 17 października, 16 września, 30 września, 8 listopada, 18 grudnia',
						'11 kwietnia, 8 maja, 18 września, 31 listopada',
						'21 kwietnia, 24 sierpnia',
						'21 września, 13 listopada',
						'1 października, 5 października',
						'1 czerwca, 3 sierpnia, 15 września',
						'14 października'),

		'characteristic' => array('Zuzanna należy do grupy pań przebojowych, łączących odwagę i pewność siebie z wrażliwością i subtelnością godną damy',
						'Julia to kobieta wrażliwa i delikatna, przypominająca kruchą, porcelanową laleczkę',
						'Lena to świetne imię dla prawdziwych ekstrawertyczek',
						'Kobiety o imieniu Maja odznaczają się nieprzeciętną ambicją.',
						'Kobieta o tym imieniu jest zazwyczaj miła i urocza, jednak pełna kompleksów, które trudno z niej wyciągnąć',
						'Zgodnie ze znaczeniem swego imienia, Zofia to ucieleśnienie mądrości i rozwagi',
						'Delikatna i krucha Amelia wydaje się być kimś nieprzystosowanym do otaczającej ją rzeczywistości',
						'Towarzyszka i lubiana, Alicja ma na ogół wielu przyjaciół i jeszcze więcej znajomych',
						'Prawdomówna i sprawiedliwa, ceni sobie fakty i szczerą prawdę bardziej niż lojalność czy przyjaźń; takie podejście często przysparza Aleksandrze kłopotów',
						'Należy do kobiet, które wiedzą, czego chcą od życia i nie boją się tego uzyskać',
						'Kobieta o tym imieniu uwielbia kwestionować czyjeś kompetencje i umiejętności, sama przy tym niewiele umiejąc',
						'Kobieta o tym imieniu zawsze chce być w centrum zainteresowania',
						'To kobieta o specyficznej osobowości, której nie da się jednoznacznie zaklasyfikować',
						'Skromna i pracowita Emilia bywa niezauważana przez wiele osób, które nawet nie zdają sobie sprawy z tego, ile tracą',
						'Antonina to urodzona konserwatystka, która hołduje tradycji i starym obyczajom',
						'Zagubiona i nie wiedząca co robić- tak najtrafniej można opisać kobietę o tym imieniu',
						'Anna to przede wszystkim osoba oddana mężowi i rodzinie; poświęca domownikom większość swojego czasu, zastanawiając się, co jeszcze mogłaby dla nich zrobić',
						'Na ogół to kobieta o arystokratycznym usposobieniu, nieco wyniosła, uważająca, że jest dużo ważniejsza i oczywiście lepsza od innych',
						'Pola to osoba wrażliwa i małomówna',
						'W przypadku kobiety o tym imieniu najlepsze jest zachowanie dystansu',
						'Antoni to mężczyzna ciekawy świata, zdolny do wielu wyrzeczeń, jeśli dzięki temu zyska jakąś istotną dla siebie wiedzę',
						'Jakub to mężczyzna dobrze zorganizowany, nie tracący czasu na próżno i nigdy nie zapominający o powierzonych mu obowiązkach',
						'Charakterystyka: Szymon na ogół stroni od ludzi i nie szuka ich towarzystwa, ma jednak nieprzeciętny dar przekonywania ich do swoich racji',
						'Osoby o imieniu Jan często stają się autorytetem dla innych ludzi',
						'Typowy Filip to osoba odznaczająca się wielkim sprytem, a wręcz przebiegłością, co sprawia, że w wielu wypadkach jest w stanie osiągnąć swój cel',
						'Franciszek to osoba cierpliwa i spokojna, którą niewiele rzeczy jest w stanie zdziwić i zaszokować',
						'Mikołaj to bardzo często osoba zarozumiała, zapatrzona w siebie, niechętnie słuchająca innych i uważająca otaczających ją ludzi za kogoś gorszego',
						'Otwarty na ludzi, komunikatywny, z dużym poczuciem humoru - Aleksander często bywa nieodzownym towarzyszem podczas wielu imprez, przyjęć czy spotkań',
						'Kacper to uosobienie pogody ducha',
						'Wojciech to osoba kochająca walkę',
						'Adamowie zazwyczaj są nieco podobni do tego biblijnego- odrobinę zarozumiali, pewni siebie i tego, że niemal zawsze mają rację',
						'Michał to osoba bardzo tajemnicza, która nie lubi, gdy ktoś wnika w jego życie prywatne, a nawet zawodowe',
						'Marcel jest osobą o łagodnym usposobieniu',
						'iktor należy do osób o dużym uroku osobistym oraz lubiących udowadniać całemu światu, że można postępować inaczej - lepiej',
						'Stanisław należy do osób zdeterminowany w dążeniu do celu, jednak nie potrafiący zrezygnować z dobrej zabawy i wspólnego spędzenia czasu ze znajomymi, nawet, jeśli do zrobienia jest coś naprawdę ważnego',
						'Opanowany i stonowany Bartosz nie należy do ludzi preferujących szybkie tempo życia',
						'Mateusz to człowiek flegmatyczny, o niezbyt bogatej osobowości, który nie lubi kłopotów ani żadnych trudności',
						'Igor to butny i nieco zarozumiały mężczyzna, który nie uznaje racji innych ludzi i uważa, że sam wie wszystko lepiej',
						'Nikodem to osoba lubiąca się dobrze bawić, o dużym poczuciu humoru, zawsze znajdująca czas na wyjście z przyjaciółmi',
						'Ugodowy, bezkonfliktowy, unikający konfrontacji'),

		'gender' => array('k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'k',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm',
						'm'),

	);
?>